### ISSUE TITLE
Charset error, invalid character

### ISSUE THREAD

**Issue by cadje** [eduardoboucas/include-media#84]
As the main SCSS file (`include-media/dist/_include-media.scss`) uses `≥` and `≤` chars, there's the following error arising:

    Invalid US-ASCII character "\xE2"

Please add `@charset "UTF-8";` as first line in those files to avoid such errors with SCSS.

Thanks in advance!

**Comment by HugoGiraudel** [comment]
How of curiosity, which compiler do you use?

**Comment by HugoGiraudel** [comment]
Done in #86. Please review @eduardoboucas.

**Comment by eduardoboucas** [comment]
Merged! Thanks guys.

**Comment by asifshirazi** [comment]
Sorry but I'm still facing this issue after updating the file :(

`(Line 262 of /private/src/sass/_include-media.scss: Invalid US-ASCII character "\xE2")`

SASS and Compass gems also updated.

**Comment by prisis** [comment]
Try to add in your config.rb 
~~~ruby
Encoding.default_external = 'utf-8'
~~~

**Comment by asifshirazi** [comment]
It works! Thank you so much @prisis :)

**Comment by prisis** [comment]
Your welcome :)

The best solution is to add ´´´´@charset 'UTF-8';´´´´ on top of all your scss/sass files. Because sometimes Ruby dont use UTF-8 as default.

**Comment by raphaelriehl** [comment]
Hello,
I have the same problem when i compile with assetic in Symfony 2.8.
In my case, i replace
`@charset 'UTF-8';`
by
`@charset "UTF-8";`
And it works fine with this solution.

If it's not conflict source, could you replace the simple quote by double quotes in the charset like the first comment ?
Thanks in advance ! :)

**Comment by HugoGiraudel** [comment]
Feel free to submit a PR. :)

**Comment by HugoGiraudel** [comment]
Done with d96611cc5896c1240607263c05a0fd3a6a30387a and 8abc8b98e91cc9135afb457eab11b85afedfba11.

**Comment by chillybin** [comment]
Getting this error when trying to compile on macOS Sierra in Grunt

```
Running "sass:build" (sass) task
Error: Invalid US-ASCII character "\xE2"
        on line 263 of bower_components/include-media/dist/_include-media.scss
        from line 5 of sass/style.scss
  Use --trace for backtrace.
Warning: Exited with error code 65 Use --force to continue.

Aborted due to warnings.

Process finished with exit code 6
```

**Comment by eduardoboucas** [comment]
Can you confirm you're using the latest version (1.4.8) of include-media?

**Comment by chillybin** [comment]
Yes that's correct
